### ISSUE TITLE
can't process heif

### ISSUE THREAD

**Issue by masterofdaemon** [twostraws/SwiftGD#43]
Hello, iv'e installed libheif, but still get  : GD Warning: gd-jpeg: JPEG library reports unrecoverable error: Not a JPEG file: starts with 0x00 0x00GD Warning: gd-webp cannot get webp info: Not a TIFF or MDI file, bad magic number 0 (0x0).
GD Warning: Cannot open TIFF imageGD Warning: one parameter to a memory allocation multiplication is negative or zero, failing operation gracefully
[ WARNING ] Abort.500: Failed to create image [request-id: 2EA88713-0238-49D5-A1C8-82331A98358A]

**Comment by twostraws** [comment]
Nowhere does this project say it supports HEIF. If you want to add HEIF support you're welcome to do so.
