### ISSUE TITLE
Loading external images

### ISSUE THREAD

**Issue by Casperhr** [twostraws/SwiftGD#7]
```
let url = "https://i.ytimg.com/vi/t34kH5eOVhM/maxresdefault.jpg"
        guard let image = Image(url: URL(fileURLWithPath: url)) else {
            print(url + " could not be loaded")
            return
        }
        print("OK")
```

Will result in "could not be loaded"

Internal images work just fine, is there a way to load external? 
Or load them via bytes?

**Comment by mRs-** [comment]
Didn't know at all the project. IMHO it would be better to handle this via `URLSession` to fetch the image.

**Comment by twostraws** [comment]
As @mRs- said this is probably better handled by other frameworks.
